### ISSUE TITLE
Email format parsing failed

### ISSUE THREAD

**Issue by Zengyf-CVer** [manoss96/pregex#5]
```python
from pregex.classes import AnyButWhitespace
from pregex.quantifiers import OneOrMore
from pregex.operators import Either

text = "My email is abcd@gmail.com"

pre = (
    OneOrMore(AnyButWhitespace())
    + "@"
    + OneOrMore(AnyButWhitespace())
    + Either(".com", ".org", ".io", ".net")
)

a = pre.get_matches(text)
print(a)
```

error report:
```shell
Traceback (most recent call last):
  File "/media/zyf/software/pregex-lab/test06.py", line 13, in <module>
    + Either(".com", ".org", ".io", ".net")
  File "/home/zyf/anaconda3/envs/py310/lib/python3.10/site-packages/pregex/operators.py", line 69, in __init__
    super().__init__(pres, lambda pre1, pre2: pre1._either(pre2), __class__._PatternType.Either)
  File "/home/zyf/anaconda3/envs/py310/lib/python3.10/site-packages/pregex/operators.py", line 17, in __init__
    result = transform(result, __class__._to_pregex(pre))
  File "/home/zyf/anaconda3/envs/py310/lib/python3.10/site-packages/pregex/operators.py", line 69, in <lambda>
    super().__init__(pres, lambda pre1, pre2: pre1._either(pre2), __class__._PatternType.Either)
AttributeError: 'str' object has no attribute '_either'
```

**Comment by manoss96** [comment]
Thanks for reporting the issue! I will make sure to fix it in the upcoming version. If you want to apply a quick fix, change line 17 in pregex.operators from:
``
result = transform(result, __class__._to_pregex(pre))
``
to
``
result = _pre.Pregex(transform(result, __class__._to_pregex(pre)), escape=False)
``
